# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
on:
  push:
    branches: [main, master]
  pull_request:

name: R-CMD-check.yaml

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          # Uncomment for R-devel checks
          # - {os: ubuntu-latest, r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,  r: 'release'}
          # Uncomment to also test on previous release
          # - {os: ubuntu-latest, r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: >
            any::rcmdcheck,
            any::roxygen2
          needs: check

      # Generate NAMESPACE + Rd files from roxygen comments
      - name: Generate Rd + NAMESPACE via roxygen2
        run: Rscript -e 'roxygen2::roxygenise(roclets = c("rd","namespace"))'

      # Install qpdf so vignette compaction works without warnings
      - name: Install qpdf (macOS)
        if: runner.os == 'macOS'
        run: brew reinstall qpdf

      - name: Install qpdf (Ubuntu)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y qpdf

      - name: Install qpdf (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: choco install qpdf --no-progress

      # Build vignettes to doc/ so we can inspect the HTML/PNG in artifacts
      - name: Build vignettes (to doc/)
        run: Rscript -e 'dir.create("doc", showWarnings = FALSE); devtools::build_vignettes()'

      # Upload built vignettes so we can inspect them after the run
      - name: Upload vignette artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-vignettes
          path: doc/

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
